### ISSUE TITLE
Mesh is distorted and flattened

### ISSUE THREAD

**Issue by Ghost---Shadow** [BennyQBD/ModernOpenGLTutorial#3]
I downloaded your code, when I run it, I get this spilling billboard.
http://imgur.com/pH7IsoH
There is no error anywhere. 

The "Mesh mesh;" in main.cpp also seems to be flattened when I render it.

I created another Monkey using Blender, the problem persists.

**Comment by Ghost---Shadow** [comment]
My graphics card probably has some compatibility issues with OpenGL 120, I made it OpenGL 330 ready and it works just fine. I will fork the repository and create a pull request ASAP. 

I modified the fragment and vertex shaders.

**Comment by BennyQBD** [comment]
The attributes aren't getting bound properly. This is an oversight on my part; for some reason I left the attribute binding calls out of this version of the repository, even though I mentioned them in the series.

Oddly enough, I'd even fixed this a while ago, but I completely forgot to commit the changes to github. I apologize for the inconvenience that my oversights have caused you.

In any case, I suggest trying the current version of the repository. It should work just fine.
