### ISSUE TITLE
fopen() function depreciated in Visual Studio

### ISSUE THREAD

**Issue by SaulDoesCode** [BennyQBD/ModernOpenGLTutorial#5]
In the file stb_image.c
There are several lines where 
FILE *f = fopen(filename,"rb");         // is used , Visual Studio  gives out an error saying it's depreciated

I fixed it with 
FILE *f;
fopen_s(&f , filename , "rb");

it seems to work :dancer:

**Comment by jellyfishcoder** [comment]
fopen_s() is exclusive to Visual Studio, and not standard C. fopen() is standard C, therefore it should be left as is, or, even better, be changed to c++ fstream. To get rid of this error, just #define _CRT_SECURE_NO_WARNINGS before including the file, which will fix the error.
